import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Collection from "../components/Collection";
import Explore from "../components/Explore";
import FoodNft from "../components/FoodNft";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Notables from "../components/Notables";
import Sidebar from "../components/Sidebar";
import Trending from "../components/Trending";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [open, setOpen] = useState(false);
  const setModal = () => {
    setOpen(!open);
  };
  console.log(open);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="relative">
        {open && (
          <div className="duration-500 ease-out">
            <Sidebar />
          </div>
        )}

        <div className="grad  ">
          {/* Navbar */}
          <Navbar setModal={setModal} />
          {/* Explore */}
          <Explore />
        </div>

        {/* Trending */}
        <Trending />
        <Collection />
        {/* Notable Collection */}
        <Notables />
        <FoodNft />
        <Footer />
      </div>
    </div>
  );
}
